#!/bin/sh

# main 강제 push 방지

# Git https url (https)
FORBIDDEN_HTTPS_URL="https://github.com/HoBom-s/hbpin-front.git"

# Git ssh url (ssh)
FORBIDDEN_SSH_URL="git@github.com:HoBom-s/hbpin-front.git"

# Branh ref
FORBIDDEN_REF="refs/heads/main"

ARR_GIT_PARAMS=($(echo $HUSKY_GIT_PARAMS))
ARR_GIT_STDIN=($(echo $HUSKY_GIT_STDIN))

remote=${ARR_GIT_PARAMS[0]}
url=${ARR_GIT_PARAMS[1]}

local_ref=${ARR_GIT_STDIN[0]}
local_sha=${ARR_GIT_STDIN[1]}
remote_ref=${ARR_GIT_STDIN[2]}
remote_sha=${ARR_GIT_STDIN[3]}

if [ "$url" != "$FORBIDDEN_HTTPS_URL" -a "$url" != "$FORBIDDEN_SSH_URL" ]
then
    exit 0 # Forked Project 에서는 제한하지 않음
fi

if [ "$remote_ref" == "$FORBIDDEN_REF" ]
then
    echo "CANNOT PUSH it main"
    # 금지된 ref 로 push 를 실행하면 에러
    exit 1 
fi

exit 0